/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authAuthImport } from './routes/(auth)/_auth'
import { Route as appAppImport } from './routes/(app)/_app'
import { Route as authAuthSignupImport } from './routes/(auth)/_auth/signup'
import { Route as authAuthSigninImport } from './routes/(auth)/_auth/signin'
import { Route as appAppTransactionsIndexImport } from './routes/(app)/_app/transactions/index'
import { Route as appAppReportingIndexImport } from './routes/(app)/_app/reporting/index'
import { Route as appAppProfileIndexImport } from './routes/(app)/_app/profile/index'
import { Route as appAppDashboardIndexImport } from './routes/(app)/_app/dashboard/index'
import { Route as appAppBudgetingIndexImport } from './routes/(app)/_app/budgeting/index'
import { Route as appAppTransactionsNewImport } from './routes/(app)/_app/transactions/new'
import { Route as appAppTransactionsTransactionIdImport } from './routes/(app)/_app/transactions/$transactionId'
import { Route as appAppReportingNewImport } from './routes/(app)/_app/reporting/new'
import { Route as appAppReportingManageImport } from './routes/(app)/_app/reporting/manage'
import { Route as appAppBudgetingNewImport } from './routes/(app)/_app/budgeting/new'
import { Route as appAppBudgetingBudgetIdIndexImport } from './routes/(app)/_app/budgeting/$budgetId/index'
import { Route as appAppTransactionsTransactionIdEditImport } from './routes/(app)/_app/transactions/$transactionId.edit'
import { Route as appAppBudgetingBudgetIdCategoriesImport } from './routes/(app)/_app/budgeting/$budgetId/categories'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()
const appImport = createFileRoute('/(app)')()

// Create/Update Routes

const authRoute = authImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appRoute = appImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const authAuthRoute = authAuthImport.update({
  id: '/_auth',
  getParentRoute: () => authRoute,
} as any)

const appAppRoute = appAppImport.update({
  id: '/_app',
  getParentRoute: () => appRoute,
} as any)

const authAuthSignupRoute = authAuthSignupImport.update({
  path: '/signup',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthSigninRoute = authAuthSigninImport.update({
  path: '/signin',
  getParentRoute: () => authAuthRoute,
} as any)

const appAppTransactionsIndexRoute = appAppTransactionsIndexImport.update({
  path: '/transactions/',
  getParentRoute: () => appAppRoute,
} as any)

const appAppReportingIndexRoute = appAppReportingIndexImport.update({
  path: '/reporting/',
  getParentRoute: () => appAppRoute,
} as any)

const appAppProfileIndexRoute = appAppProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => appAppRoute,
} as any)

const appAppDashboardIndexRoute = appAppDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => appAppRoute,
} as any)

const appAppBudgetingIndexRoute = appAppBudgetingIndexImport.update({
  path: '/budgeting/',
  getParentRoute: () => appAppRoute,
} as any)

const appAppTransactionsNewRoute = appAppTransactionsNewImport.update({
  path: '/transactions/new',
  getParentRoute: () => appAppRoute,
} as any)

const appAppTransactionsTransactionIdRoute =
  appAppTransactionsTransactionIdImport.update({
    path: '/transactions/$transactionId',
    getParentRoute: () => appAppRoute,
  } as any)

const appAppReportingNewRoute = appAppReportingNewImport.update({
  path: '/reporting/new',
  getParentRoute: () => appAppRoute,
} as any)

const appAppReportingManageRoute = appAppReportingManageImport.update({
  path: '/reporting/manage',
  getParentRoute: () => appAppRoute,
} as any)

const appAppBudgetingNewRoute = appAppBudgetingNewImport.update({
  path: '/budgeting/new',
  getParentRoute: () => appAppRoute,
} as any)

const appAppBudgetingBudgetIdIndexRoute =
  appAppBudgetingBudgetIdIndexImport.update({
    path: '/budgeting/$budgetId/',
    getParentRoute: () => appAppRoute,
  } as any)

const appAppTransactionsTransactionIdEditRoute =
  appAppTransactionsTransactionIdEditImport.update({
    path: '/edit',
    getParentRoute: () => appAppTransactionsTransactionIdRoute,
  } as any)

const appAppBudgetingBudgetIdCategoriesRoute =
  appAppBudgetingBudgetIdCategoriesImport.update({
    path: '/budgeting/$budgetId/categories',
    getParentRoute: () => appAppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_app': {
      id: '/(app)/_app'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appAppImport
      parentRoute: typeof appRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_auth/signin': {
      id: '/(auth)/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authAuthSigninImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/signup': {
      id: '/(auth)/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authAuthSignupImport
      parentRoute: typeof authAuthImport
    }
    '/(app)/_app/budgeting/new': {
      id: '/(app)/_app/budgeting/new'
      path: '/budgeting/new'
      fullPath: '/budgeting/new'
      preLoaderRoute: typeof appAppBudgetingNewImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/reporting/manage': {
      id: '/(app)/_app/reporting/manage'
      path: '/reporting/manage'
      fullPath: '/reporting/manage'
      preLoaderRoute: typeof appAppReportingManageImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/reporting/new': {
      id: '/(app)/_app/reporting/new'
      path: '/reporting/new'
      fullPath: '/reporting/new'
      preLoaderRoute: typeof appAppReportingNewImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/transactions/$transactionId': {
      id: '/(app)/_app/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof appAppTransactionsTransactionIdImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/transactions/new': {
      id: '/(app)/_app/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof appAppTransactionsNewImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/budgeting/': {
      id: '/(app)/_app/budgeting/'
      path: '/budgeting'
      fullPath: '/budgeting'
      preLoaderRoute: typeof appAppBudgetingIndexImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/dashboard/': {
      id: '/(app)/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appAppDashboardIndexImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/profile/': {
      id: '/(app)/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appAppProfileIndexImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/reporting/': {
      id: '/(app)/_app/reporting/'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof appAppReportingIndexImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/transactions/': {
      id: '/(app)/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof appAppTransactionsIndexImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/budgeting/$budgetId/categories': {
      id: '/(app)/_app/budgeting/$budgetId/categories'
      path: '/budgeting/$budgetId/categories'
      fullPath: '/budgeting/$budgetId/categories'
      preLoaderRoute: typeof appAppBudgetingBudgetIdCategoriesImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/transactions/$transactionId/edit': {
      id: '/(app)/_app/transactions/$transactionId/edit'
      path: '/edit'
      fullPath: '/transactions/$transactionId/edit'
      preLoaderRoute: typeof appAppTransactionsTransactionIdEditImport
      parentRoute: typeof appAppTransactionsTransactionIdImport
    }
    '/(app)/_app/budgeting/$budgetId/': {
      id: '/(app)/_app/budgeting/$budgetId/'
      path: '/budgeting/$budgetId'
      fullPath: '/budgeting/$budgetId'
      preLoaderRoute: typeof appAppBudgetingBudgetIdIndexImport
      parentRoute: typeof appAppImport
    }
  }
}

// Create and export the route tree

interface appAppTransactionsTransactionIdRouteChildren {
  appAppTransactionsTransactionIdEditRoute: typeof appAppTransactionsTransactionIdEditRoute
}

const appAppTransactionsTransactionIdRouteChildren: appAppTransactionsTransactionIdRouteChildren =
  {
    appAppTransactionsTransactionIdEditRoute:
      appAppTransactionsTransactionIdEditRoute,
  }

const appAppTransactionsTransactionIdRouteWithChildren =
  appAppTransactionsTransactionIdRoute._addFileChildren(
    appAppTransactionsTransactionIdRouteChildren,
  )

interface appAppRouteChildren {
  appAppBudgetingNewRoute: typeof appAppBudgetingNewRoute
  appAppReportingManageRoute: typeof appAppReportingManageRoute
  appAppReportingNewRoute: typeof appAppReportingNewRoute
  appAppTransactionsTransactionIdRoute: typeof appAppTransactionsTransactionIdRouteWithChildren
  appAppTransactionsNewRoute: typeof appAppTransactionsNewRoute
  appAppBudgetingIndexRoute: typeof appAppBudgetingIndexRoute
  appAppDashboardIndexRoute: typeof appAppDashboardIndexRoute
  appAppProfileIndexRoute: typeof appAppProfileIndexRoute
  appAppReportingIndexRoute: typeof appAppReportingIndexRoute
  appAppTransactionsIndexRoute: typeof appAppTransactionsIndexRoute
  appAppBudgetingBudgetIdCategoriesRoute: typeof appAppBudgetingBudgetIdCategoriesRoute
  appAppBudgetingBudgetIdIndexRoute: typeof appAppBudgetingBudgetIdIndexRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppBudgetingNewRoute: appAppBudgetingNewRoute,
  appAppReportingManageRoute: appAppReportingManageRoute,
  appAppReportingNewRoute: appAppReportingNewRoute,
  appAppTransactionsTransactionIdRoute:
    appAppTransactionsTransactionIdRouteWithChildren,
  appAppTransactionsNewRoute: appAppTransactionsNewRoute,
  appAppBudgetingIndexRoute: appAppBudgetingIndexRoute,
  appAppDashboardIndexRoute: appAppDashboardIndexRoute,
  appAppProfileIndexRoute: appAppProfileIndexRoute,
  appAppReportingIndexRoute: appAppReportingIndexRoute,
  appAppTransactionsIndexRoute: appAppTransactionsIndexRoute,
  appAppBudgetingBudgetIdCategoriesRoute:
    appAppBudgetingBudgetIdCategoriesRoute,
  appAppBudgetingBudgetIdIndexRoute: appAppBudgetingBudgetIdIndexRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface appRouteChildren {
  appAppRoute: typeof appAppRouteWithChildren
}

const appRouteChildren: appRouteChildren = {
  appAppRoute: appAppRouteWithChildren,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface authAuthRouteChildren {
  authAuthSigninRoute: typeof authAuthSigninRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthSigninRoute: authAuthSigninRoute,
  authAuthSignupRoute: authAuthSignupRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authAuthRouteWithChildren
  '/signin': typeof authAuthSigninRoute
  '/signup': typeof authAuthSignupRoute
  '/budgeting/new': typeof appAppBudgetingNewRoute
  '/reporting/manage': typeof appAppReportingManageRoute
  '/reporting/new': typeof appAppReportingNewRoute
  '/transactions/$transactionId': typeof appAppTransactionsTransactionIdRouteWithChildren
  '/transactions/new': typeof appAppTransactionsNewRoute
  '/budgeting': typeof appAppBudgetingIndexRoute
  '/dashboard': typeof appAppDashboardIndexRoute
  '/profile': typeof appAppProfileIndexRoute
  '/reporting': typeof appAppReportingIndexRoute
  '/transactions': typeof appAppTransactionsIndexRoute
  '/budgeting/$budgetId/categories': typeof appAppBudgetingBudgetIdCategoriesRoute
  '/transactions/$transactionId/edit': typeof appAppTransactionsTransactionIdEditRoute
  '/budgeting/$budgetId': typeof appAppBudgetingBudgetIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authAuthRouteWithChildren
  '/signin': typeof authAuthSigninRoute
  '/signup': typeof authAuthSignupRoute
  '/budgeting/new': typeof appAppBudgetingNewRoute
  '/reporting/manage': typeof appAppReportingManageRoute
  '/reporting/new': typeof appAppReportingNewRoute
  '/transactions/$transactionId': typeof appAppTransactionsTransactionIdRouteWithChildren
  '/transactions/new': typeof appAppTransactionsNewRoute
  '/budgeting': typeof appAppBudgetingIndexRoute
  '/dashboard': typeof appAppDashboardIndexRoute
  '/profile': typeof appAppProfileIndexRoute
  '/reporting': typeof appAppReportingIndexRoute
  '/transactions': typeof appAppTransactionsIndexRoute
  '/budgeting/$budgetId/categories': typeof appAppBudgetingBudgetIdCategoriesRoute
  '/transactions/$transactionId/edit': typeof appAppTransactionsTransactionIdEditRoute
  '/budgeting/$budgetId': typeof appAppBudgetingBudgetIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)': typeof appRouteWithChildren
  '/(app)/_app': typeof appAppRouteWithChildren
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/_auth/signin': typeof authAuthSigninRoute
  '/(auth)/_auth/signup': typeof authAuthSignupRoute
  '/(app)/_app/budgeting/new': typeof appAppBudgetingNewRoute
  '/(app)/_app/reporting/manage': typeof appAppReportingManageRoute
  '/(app)/_app/reporting/new': typeof appAppReportingNewRoute
  '/(app)/_app/transactions/$transactionId': typeof appAppTransactionsTransactionIdRouteWithChildren
  '/(app)/_app/transactions/new': typeof appAppTransactionsNewRoute
  '/(app)/_app/budgeting/': typeof appAppBudgetingIndexRoute
  '/(app)/_app/dashboard/': typeof appAppDashboardIndexRoute
  '/(app)/_app/profile/': typeof appAppProfileIndexRoute
  '/(app)/_app/reporting/': typeof appAppReportingIndexRoute
  '/(app)/_app/transactions/': typeof appAppTransactionsIndexRoute
  '/(app)/_app/budgeting/$budgetId/categories': typeof appAppBudgetingBudgetIdCategoriesRoute
  '/(app)/_app/transactions/$transactionId/edit': typeof appAppTransactionsTransactionIdEditRoute
  '/(app)/_app/budgeting/$budgetId/': typeof appAppBudgetingBudgetIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/budgeting/new'
    | '/reporting/manage'
    | '/reporting/new'
    | '/transactions/$transactionId'
    | '/transactions/new'
    | '/budgeting'
    | '/dashboard'
    | '/profile'
    | '/reporting'
    | '/transactions'
    | '/budgeting/$budgetId/categories'
    | '/transactions/$transactionId/edit'
    | '/budgeting/$budgetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/budgeting/new'
    | '/reporting/manage'
    | '/reporting/new'
    | '/transactions/$transactionId'
    | '/transactions/new'
    | '/budgeting'
    | '/dashboard'
    | '/profile'
    | '/reporting'
    | '/transactions'
    | '/budgeting/$budgetId/categories'
    | '/transactions/$transactionId/edit'
    | '/budgeting/$budgetId'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/_app'
    | '/(auth)'
    | '/(auth)/_auth'
    | '/(auth)/_auth/signin'
    | '/(auth)/_auth/signup'
    | '/(app)/_app/budgeting/new'
    | '/(app)/_app/reporting/manage'
    | '/(app)/_app/reporting/new'
    | '/(app)/_app/transactions/$transactionId'
    | '/(app)/_app/transactions/new'
    | '/(app)/_app/budgeting/'
    | '/(app)/_app/dashboard/'
    | '/(app)/_app/profile/'
    | '/(app)/_app/reporting/'
    | '/(app)/_app/transactions/'
    | '/(app)/_app/budgeting/$budgetId/categories'
    | '/(app)/_app/transactions/$transactionId/edit'
    | '/(app)/_app/budgeting/$budgetId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  authRoute: typeof authRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  authRoute: authRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)",
        "/(auth)"
      ]
    },
    "/(app)": {
      "filePath": "(app)",
      "children": [
        "/(app)/_app"
      ]
    },
    "/(app)/_app": {
      "filePath": "(app)/_app.tsx",
      "parent": "/(app)",
      "children": [
        "/(app)/_app/budgeting/new",
        "/(app)/_app/reporting/manage",
        "/(app)/_app/reporting/new",
        "/(app)/_app/transactions/$transactionId",
        "/(app)/_app/transactions/new",
        "/(app)/_app/budgeting/",
        "/(app)/_app/dashboard/",
        "/(app)/_app/profile/",
        "/(app)/_app/reporting/",
        "/(app)/_app/transactions/",
        "/(app)/_app/budgeting/$budgetId/categories",
        "/(app)/_app/budgeting/$budgetId/"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth"
      ]
    },
    "/(auth)/_auth": {
      "filePath": "(auth)/_auth.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth/signin",
        "/(auth)/_auth/signup"
      ]
    },
    "/(auth)/_auth/signin": {
      "filePath": "(auth)/_auth/signin.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/signup": {
      "filePath": "(auth)/_auth/signup.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(app)/_app/budgeting/new": {
      "filePath": "(app)/_app/budgeting/new.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/reporting/manage": {
      "filePath": "(app)/_app/reporting/manage.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/reporting/new": {
      "filePath": "(app)/_app/reporting/new.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/transactions/$transactionId": {
      "filePath": "(app)/_app/transactions/$transactionId.tsx",
      "parent": "/(app)/_app",
      "children": [
        "/(app)/_app/transactions/$transactionId/edit"
      ]
    },
    "/(app)/_app/transactions/new": {
      "filePath": "(app)/_app/transactions/new.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/budgeting/": {
      "filePath": "(app)/_app/budgeting/index.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/dashboard/": {
      "filePath": "(app)/_app/dashboard/index.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/profile/": {
      "filePath": "(app)/_app/profile/index.ts",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/reporting/": {
      "filePath": "(app)/_app/reporting/index.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/transactions/": {
      "filePath": "(app)/_app/transactions/index.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/budgeting/$budgetId/categories": {
      "filePath": "(app)/_app/budgeting/$budgetId/categories.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/transactions/$transactionId/edit": {
      "filePath": "(app)/_app/transactions/$transactionId.edit.tsx",
      "parent": "/(app)/_app/transactions/$transactionId"
    },
    "/(app)/_app/budgeting/$budgetId/": {
      "filePath": "(app)/_app/budgeting/$budgetId/index.tsx",
      "parent": "/(app)/_app"
    }
  }
}
ROUTE_MANIFEST_END */
